/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bmSys.groupChat;

import java.io.IOException;
import java.net.Socket;
import javax.swing.DefaultListModel;

/**
 *
 * @author Admin
 */
public class GroupChat extends javax.swing.JFrame {

    private DefaultListModel<String> JlistModel = new DefaultListModel<>();
    private Client client;
    private Socket socket;

    /**
     * Creates new form GroupChat
     */
    public GroupChat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textSend = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listChat = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Group Chat");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSendActionPerformed(evt);
            }
        });
        getContentPane().add(textSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 330, -1));

        btnSend.setText("Send");
        btnSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSendMouseClicked(evt);
            }
        });
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        getContentPane().add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, -1, -1));

        listChat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listChat.setModel(JlistModel);
        jScrollPane2.setViewportView(listChat);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        sendMsg();


    }//GEN-LAST:event_btnSendActionPerformed

    private void textSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSendActionPerformed

    private void btnSendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnSendMouseClicked
    public static void main(String[] args) {
        GroupChat gc = new GroupChat();
        gc.setVisible(true);
        gc.initClient();

    }

    public void initClient() {
        try {
            socket = new Socket("localhost", 1234);
            client = new Client(socket, "zz");
            new ReadThread(client, JlistModel).start();

        } catch (IOException ex) {
            System.out.println(ex);
        }
    }

    public void sendMsg() {
        new SendThread(client, textSend, JlistModel).start();
  
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listChat;
    private javax.swing.JTextField textSend;
    // End of variables declaration//GEN-END:variables
}
