/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bmSys.ui.admin;

import com.bmSys.dao.AdminDAO;
import com.bmSys.dao.CustomerDAO;
import com.bmSys.dao.EmployeeDAO;
import com.bmSys.mapper.CustomerMapper;
import com.bmSys.mapper.EmployeeMapper;
import com.bmSys.model.AdminModel;
import com.bmSys.model.CustomerModel;
import com.bmSys.model.EmployeeModel;
import com.bmSys.utils.MsgBoxUtil;
import com.bmSys.utils.Validator;
import java.util.List;

import com.bmSys.utils.XDate;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Integ
 */
public class Home extends javax.swing.JFrame {
    private String pathImg = "";
    /**
     * Creates new form AdminHome
     */
    public Home(AdminModel model) {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        pnlemp = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtEID = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUN = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAdress = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        dcBirth = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtUN1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbltitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblLogOut = new javax.swing.JLabel();
        lblUC = new javax.swing.JLabel();
        lblUE = new javax.swing.JLabel();
        lblCE = new javax.swing.JLabel();
        pnlemplist = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbllistemp = new javax.swing.JTable();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        pnlcusomer = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblcust = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlemp.setBackground(new java.awt.Color(255, 255, 255));
        pnlemp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlemp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/id-card.png"))); // NOI18N
        jLabel5.setText("Employee ID");
        pnlemp.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 12, 120, -1));

        txtEID.setEditable(false);
        pnlemp.add(txtEID, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 15, 284, -1));

        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlemp.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 145, 163));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/user1.png"))); // NOI18N
        jLabel6.setText("Name             ");
        pnlemp.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 120, -1));
        pnlemp.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 284, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/username.png"))); // NOI18N
        jLabel7.setText("Username      ");
        pnlemp.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 120, -1));
        pnlemp.add(txtUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 284, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/Adress.png"))); // NOI18N
        jLabel10.setText("Adress           ");
        pnlemp.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        txtAdress.setColumns(20);
        txtAdress.setRows(5);
        jScrollPane1.setViewportView(txtAdress);

        pnlemp.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 286, 70));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/email.png"))); // NOI18N
        jLabel11.setText("Email             ");
        pnlemp.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        pnlemp.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 286, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/phone-call.png"))); // NOI18N
        jLabel12.setText("Contact        ");
        pnlemp.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));
        pnlemp.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 286, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/birthday.png"))); // NOI18N
        jLabel14.setText("Birthday     ");
        pnlemp.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 428, -1, -1));

        btnsubmit.setBackground(new java.awt.Color(51, 204, 255));
        btnsubmit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnsubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/check.png"))); // NOI18N
        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        pnlemp.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 470, 120, 36));

        btnrefresh.setBackground(new java.awt.Color(51, 204, 255));
        btnrefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnrefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/refresh.png"))); // NOI18N
        btnrefresh.setText("Refresh");
        pnlemp.add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 470, 133, 36));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("Upload");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        pnlemp.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 211, -1, -1));
        pnlemp.add(dcBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 290, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel9.setText("Password");
        pnlemp.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));
        pnlemp.add(txtUN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 284, -1));

        getContentPane().add(pnlemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 770, 560));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin Portal");

        lbltitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(255, 255, 255));
        lbltitle.setText("Create Employee");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/calendar.png"))); // NOI18N
        jLabel3.setText("Date:");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/clock.png"))); // NOI18N
        jLabel4.setText("Time:");

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("jLabel16");

        lblClock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblClock.setForeground(new java.awt.Color(255, 255, 255));
        lblClock.setText("jLabel16");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261)
                .addComponent(lbltitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltitle)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblClock))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 60));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 980, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/menu.png"))); // NOI18N
        jLabel2.setText("Menu");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 210, -1));

        lblLogOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/logout.png"))); // NOI18N
        lblLogOut.setText("Logout");
        lblLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogOutMouseExited(evt);
            }
        });
        jPanel3.add(lblLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 210, 50));

        lblUC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/user.png"))); // NOI18N
        lblUC.setText("Update Customer");
        lblUC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUCMouseExited(evt);
            }
        });
        jPanel3.add(lblUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 210, 50));

        lblUE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/update.png"))); // NOI18N
        lblUE.setText("Update Employee");
        lblUE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUEMouseExited(evt);
            }
        });
        jPanel3.add(lblUE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 210, 50));

        lblCE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/add-user.png"))); // NOI18N
        lblCE.setText("Create Employee");
        lblCE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCEMouseExited(evt);
            }
        });
        jPanel3.add(lblCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 210, 560));

        pnlemplist.setBackground(new java.awt.Color(255, 255, 255));
        pnlemplist.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlemplist.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbllistemp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_nhanVien", "hoTen", "diaChi", "soDT", "email"
            }
        ));
        jScrollPane3.setViewportView(tbllistemp);

        pnlemplist.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 700, 350));

        btnadd.setText("Add");
        pnlemplist.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        pnlemplist.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        btndel.setText("Delete");
        pnlemplist.add(btndel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, -1));

        getContentPane().add(pnlemplist, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 770, 560));

        pnlcusomer.setBackground(new java.awt.Color(255, 255, 255));
        pnlcusomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlcusomer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("Customer List");
        pnlcusomer.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 187, -1));

        tblcust.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_customer", "HoTen", "DiaChi", "SoDT", "Email"
            }
        ));
        jScrollPane2.setViewportView(tblcust);

        pnlcusomer.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 690, 350));

        jButton1.setText("Add");
        pnlcusomer.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        jButton2.setText("Update");
        pnlcusomer.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        jButton3.setText("Delete");
        pnlcusomer.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, -1, -1));

        getContentPane().add(pnlcusomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 770, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        saveNewEmployee();
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnupdateActionPerformed

    private void lblCEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCEMouseClicked
        // TODO add your handling code here:
        showPanelMenu(pnlemp);
        lbltitle.setText("Create Employee");
    }//GEN-LAST:event_lblCEMouseClicked

    private void lblCEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCEMouseEntered
        // TODO add your handling code here:
        hoverMenu(lblCE);
    }//GEN-LAST:event_lblCEMouseEntered

    private void lblUEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUEMouseClicked
        // TODO add your handling code here:
        showPanelMenu(pnlemplist);
        lbltitle.setText("Employee List");
        loadDataToTable(tbllistemp);
    }//GEN-LAST:event_lblUEMouseClicked

    private void lblUEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUEMouseEntered
        // TODO add your handling code here:
        hoverMenu(lblUE);
    }//GEN-LAST:event_lblUEMouseEntered

    private void lblUEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUEMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_lblUEMouseExited

    private void lblCEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCEMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_lblCEMouseExited

    private void lblUCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUCMouseClicked
        // TODO add your handling code here:
        showPanelMenu(pnlcusomer);
        lbltitle.setText("Customer List");
        loadDataToTable(tblcust);
    }//GEN-LAST:event_lblUCMouseClicked

    private void lblUCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUCMouseEntered
        // TODO add your handling code here:
        hoverMenu(lblUC);
    }//GEN-LAST:event_lblUCMouseEntered

    private void lblUCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUCMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_lblUCMouseExited

    private void lblLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseClicked
        // TODO add your handling code here:
        logOut();
    }//GEN-LAST:event_lblLogOutMouseClicked

    private void lblLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseEntered
        // TODO add your handling code here:
        hoverMenu(lblLogOut);
    }//GEN-LAST:event_lblLogOutMouseEntered

    private void lblLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_lblLogOutMouseExited

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int option = fc.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            String pathImgDefault = file.getPath();
             pathImg ="nv_"+ pathImgDefault.split("_")[1];
              resizeImage(pathImg);
        }

    }//GEN-LAST:event_jLabel15MouseClicked

    private void init() {
        setLocationRelativeTo(null);
        XDate.showTime(lblDate, "dd/MM/yyyy");
        XDate.showTime(lblClock, "hh:mm:ss a");
        showPanelMenu(pnlemp);
        tableDesign(tblcust);
        tableDesign(tbllistemp);
    }

    private void showPanelMenu(JPanel pnl) {
        pnlcusomer.setVisible(false);
        pnlemplist.setVisible(false);
        pnlemp.setVisible(false);
        renderNewId();
        pnl.setVisible(true);
    }

    private void hoverMenu(JLabel lbl) {
        //setColorMenuItem();
        // set color button
        lbl.setBackground(new Color(51, 153, 255));
        lbl.setForeground(Color.white);

    }

    private void setColorMenuItem() {
        // set color button
        lblCE.setBackground(new Color(255, 255, 255));
        lblClock.setBackground(new Color(255, 255, 255));
        lblLogOut.setBackground(new Color(255, 255, 255));
        lblDate.setBackground(new Color(255, 255, 255));
        lblUC.setBackground(new Color(255, 255, 255));
        lblUE.setBackground(new Color(255, 255, 255));
        lblCE.setForeground(Color.black);
        lblClock.setForeground(Color.black);
        lblLogOut.setForeground(Color.black);
        lblDate.setForeground(Color.black);
        lblUC.setForeground(Color.black);
        lblUE.setForeground(Color.black);

    }

    private void logOut() {
        boolean b = MsgBoxUtil.confirm(this, "Do you want to logout?");
        if (b) {
            AdminDAO dao = new AdminDAO();
            this.dispose();
            Login login = new Login();
            login.setVisible(true);
        }
    }

    private void loadDataToTable(JTable table, JDateChooser... dateChoosers) {
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        dtm.setRowCount(0);

        if (table == tbllistemp) {
            EmployeeDAO ctDao = new EmployeeDAO();
            List<EmployeeModel> listemp = ctDao.findAll();
            for (EmployeeModel emp : listemp) {
                dtm.addRow(new EmployeeMapper().mapper(emp));
            }
        } else if (table == tblcust) {
            CustomerDAO ctDao = new CustomerDAO();
            List<CustomerModel> listCust = ctDao.findAll();
            for (CustomerModel cus : listCust) {
                dtm.addRow(new CustomerMapper().mapper(cus));
            }
        }
    }

    private void tableDesign(JTable tbl) {
        DefaultTableCellRenderer head_render = new DefaultTableCellRenderer();
        head_render.setPreferredSize(new Dimension(30, 40));
        head_render.setBackground(new Color(32, 136, 203));
        head_render.setForeground(new Color(255, 255, 255));
        head_render.setFont(new Font("Segoe UI", Font.BOLD, 14));
        //do rong cac cot
//        setColumnWidths(tbl,30, 150, 100, 100);
        tbl.getTableHeader().setDefaultRenderer(head_render);
        tbl.setRowHeight(35);
        tbl.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tbl.setBackground(Color.white);
    }

    private void saveNewEmployee() {
        if (CreateAccValidation()) {
            boolean a = MsgBoxUtil.confirm(this, "Do you want to create new Employee?");
            if (a) {
                EmployeeModel newModel = new EmployeeModel();
                newModel.setId(txtEID.getText());
                newModel.setHoTen(txtname.getText());
                newModel.setDiaChi(txtAdress.getText());
                newModel.setSoDT(txtContact.getText());

                newModel.setNgaySinh(dcBirth.getDate());
                newModel.setEmail(txtEmail.getText());
                newModel.setUsername(txtUN1.getText());
                newModel.setPassword(txtUN.getText());
                newModel.setLinkImg(pathImg);
                EmployeeDAO dao = new EmployeeDAO();
                dao.saveOne(newModel);

            }
        }
    }

    private boolean CreateAccValidation() {
        String error = "";
        //Name
        if (Validator.checkEmpty(txtname)) {
            error += "Name cannot be null!\n";
        }
        //Address
        if (Validator.checkEmptyArea(txtAdress)) {
            error += "Address cannot be null!\n";
        }
        //Contact
        if (Validator.checkEmpty(txtContact)) {
            error += "Contact cannot be null!\n";
        }
        if (Validator.checkPhone(txtContact)) {
            error += "Contact must be 10 numbers!\n";
        }
        //Birth
        if (Validator.checkDate(dcBirth)) {
            error += "Birth must be in dd-MM-yyyy!\n";
        }
        //Email
        if (Validator.checkEmpty(txtEmail)) {
            error += "Email cannot be null!\n";
        }
        if (Validator.checkEmail(txtEmail)) {
            error += "Wrong email format!\n";
        }
        //Submit
        if (!error.equals("")) {
            JOptionPane.showMessageDialog(null, error);
            return false;
        } else {
            return true;
        }
    }

    private void renderNewId() {
        EmployeeDAO dao = new EmployeeDAO();
        String new_id = "";

        String id = dao.findOne().getId();
         int id_num = Integer.valueOf(id.split("_")[1].substring(0,3));

        if (id_num + 1 < 10) {
            new_id = "00" + (id_num + 1);
        } else {
            new_id = "0" + (id_num + 1);
        }
        txtEID.setText("NV_" + new_id);
    }
    
        private void resizeImage(String link ) {
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/com/bmSys/image/" + link));
        Image img = imageIcon.getImage();
        Image dimg = img.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(),
                Image.SCALE_SMOOTH);
        ImageIcon scaleIcon = new ImageIcon(dimg);
        lblImage.setIcon(scaleIcon);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JButton btnupdate;
    private com.toedter.calendar.JDateChooser dcBirth;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCE;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLogOut;
    private javax.swing.JLabel lblUC;
    private javax.swing.JLabel lblUE;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JPanel pnlcusomer;
    private javax.swing.JPanel pnlemp;
    private javax.swing.JPanel pnlemplist;
    private javax.swing.JTable tblcust;
    private javax.swing.JTable tbllistemp;
    private javax.swing.JTextArea txtAdress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEID;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtUN;
    private javax.swing.JTextField txtUN1;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
