/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bmSys.ui.admin;

import com.bmSys.dao.AccountDAO;
import com.bmSys.dao.AdminDAO;
import com.bmSys.dao.CustomerDAO;
import com.bmSys.dao.EmployeeDAO;
import com.bmSys.dao.TransactionDAO;
import com.bmSys.mapper.CustomerMapper;
import com.bmSys.mapper.EmployeeMapper;
import com.bmSys.mapper.TransactionMapper;
import com.bmSys.model.CustomerModel;
import com.bmSys.model.EmployeeModel;
import com.bmSys.model.TransactionModel;
import com.bmSys.utils.GuiUtil;
import com.bmSys.utils.MsgBoxUtil;
import com.bmSys.utils.Validator;
import java.util.List;

import com.bmSys.utils.XDate;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Integ
 */
public class Home extends javax.swing.JFrame {

    private String pathImg = "";
    private TableRowSorter sorter;
    AccountDAO acDao = new AccountDAO();
    EmployeeDAO epDao = new EmployeeDAO();
    CustomerDAO ctDao = new CustomerDAO();
    TransactionDAO ttDao = new TransactionDAO();

    /**
     * Creates new form AdminHome
     */
    public Home() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        pnlemp = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtEID = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUN = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAdress = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUN1 = new javax.swing.JTextField();
        dcBirth = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbltitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        btnHelp = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblLogOut = new javax.swing.JLabel();
        lblUC = new javax.swing.JLabel();
        lblUE = new javax.swing.JLabel();
        lblCE = new javax.swing.JLabel();
        lblStatistics = new javax.swing.JLabel();
        pnlemplist = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbllistemp = new javax.swing.JTable();
        btnupdate = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtid_empl = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtname_empl = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtadress_empl = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtphone_empl = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtemail_empl = new javax.swing.JTextField();
        pnlcusomer = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblcust = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtid_cust = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtname_cust = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtadress_cust = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtphone_cust = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtemail_cust = new javax.swing.JTextField();
        pnlStatistics = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtFindID = new javax.swing.JTextField();
        dcDate = new com.toedter.calendar.JDateChooser();
        jLabel33 = new javax.swing.JLabel();
        cbbType = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblMoneyNap = new javax.swing.JLabel();
        lblMoneyRut = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTrans = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlemp.setBackground(new java.awt.Color(255, 255, 255));
        pnlemp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlemp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/id-card.png"))); // NOI18N
        jLabel5.setText("Employee ID");
        pnlemp.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 120, -1));

        txtEID.setEditable(false);
        pnlemp.add(txtEID, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 15, 284, -1));

        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlemp.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 145, 163));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/user1.png"))); // NOI18N
        jLabel6.setText("Name             ");
        pnlemp.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 120, -1));
        pnlemp.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 284, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/username.png"))); // NOI18N
        jLabel7.setText("Username      ");
        pnlemp.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 120, -1));
        pnlemp.add(txtUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 284, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/Adress.png"))); // NOI18N
        jLabel10.setText("Adress           ");
        pnlemp.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        txtAdress.setColumns(20);
        txtAdress.setRows(5);
        jScrollPane1.setViewportView(txtAdress);

        pnlemp.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 286, 70));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/email.png"))); // NOI18N
        jLabel11.setText("Email             ");
        pnlemp.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));
        pnlemp.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 286, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/phone-call.png"))); // NOI18N
        jLabel12.setText("Contact        ");
        pnlemp.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));
        pnlemp.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 286, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/birthday.png"))); // NOI18N
        jLabel14.setText("Birthday     ");
        pnlemp.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 428, -1, -1));

        btnsubmit.setBackground(new java.awt.Color(51, 204, 255));
        btnsubmit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnsubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/check.png"))); // NOI18N
        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        pnlemp.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 470, 120, 36));

        btnrefresh.setBackground(new java.awt.Color(51, 204, 255));
        btnrefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnrefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/refresh.png"))); // NOI18N
        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        pnlemp.add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 470, 133, 36));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("Upload");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        pnlemp.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 211, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/password.png"))); // NOI18N
        jLabel9.setText("Password");
        pnlemp.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));
        pnlemp.add(txtUN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 284, -1));
        pnlemp.add(dcBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 290, -1));

        getContentPane().add(pnlemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 770, 560));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin Portal");

        lbltitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(255, 255, 255));
        lbltitle.setText("Create Employee");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/calendar.png"))); // NOI18N
        jLabel3.setText("Date:");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/clock.png"))); // NOI18N
        jLabel4.setText("Time:");

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("jLabel16");

        lblClock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblClock.setForeground(new java.awt.Color(255, 255, 255));
        lblClock.setText("jLabel16");

        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/question-mark24.png"))); // NOI18N
        btnHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHelpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261)
                .addComponent(lbltitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblClock, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltitle)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblClock)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHelp)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 60));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 980, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/menu.png"))); // NOI18N
        jLabel2.setText("Menu");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 210, -1));

        lblLogOut.setBackground(new java.awt.Color(255, 255, 255));
        lblLogOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/logout.png"))); // NOI18N
        lblLogOut.setText("Logout");
        lblLogOut.setOpaque(true);
        lblLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogOutMouseExited(evt);
            }
        });
        jPanel3.add(lblLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 210, 50));

        lblUC.setBackground(new java.awt.Color(255, 255, 255));
        lblUC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/user.png"))); // NOI18N
        lblUC.setText("Update Customer");
        lblUC.setOpaque(true);
        lblUC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUCMouseExited(evt);
            }
        });
        jPanel3.add(lblUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 210, 50));

        lblUE.setBackground(new java.awt.Color(255, 255, 255));
        lblUE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/update.png"))); // NOI18N
        lblUE.setText("Update Employee");
        lblUE.setOpaque(true);
        lblUE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUEMouseExited(evt);
            }
        });
        jPanel3.add(lblUE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 210, 50));

        lblCE.setBackground(new java.awt.Color(255, 255, 255));
        lblCE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/add-user.png"))); // NOI18N
        lblCE.setText("Create Employee");
        lblCE.setOpaque(true);
        lblCE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCEMouseExited(evt);
            }
        });
        jPanel3.add(lblCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 210, 50));

        lblStatistics.setBackground(new java.awt.Color(255, 255, 255));
        lblStatistics.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStatistics.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatistics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bmSys/icon/data-table.png"))); // NOI18N
        lblStatistics.setText("Statistics");
        lblStatistics.setOpaque(true);
        lblStatistics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStatisticsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblStatisticsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblStatisticsMouseExited(evt);
            }
        });
        jPanel3.add(lblStatistics, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 210, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 210, 560));

        pnlemplist.setBackground(new java.awt.Color(255, 255, 255));
        pnlemplist.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlemplist.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbllistemp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_nhanVien", "hoTen", "diaChi", "soDT", "email"
            }
        ));
        tbllistemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbllistempMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tbllistemp);

        pnlemplist.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 700, 350));

        btnupdate.setBackground(new java.awt.Color(0, 153, 255));
        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        pnlemplist.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, -1, -1));

        btndel.setBackground(new java.awt.Color(0, 153, 255));
        btndel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btndel.setForeground(new java.awt.Color(255, 255, 255));
        btndel.setText("Delete");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });
        pnlemplist.add(btndel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, -1, -1));

        jLabel8.setText("ID_NhanVien");
        pnlemplist.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 70, 20));

        txtid_empl.setEditable(false);
        pnlemplist.add(txtid_empl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 190, -1));

        jLabel13.setText("Họ Tên");
        pnlemplist.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 70, 20));
        pnlemplist.add(txtname_empl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 190, -1));

        jLabel16.setText("Địa Chỉ");
        pnlemplist.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 70, 20));
        pnlemplist.add(txtadress_empl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 190, -1));

        jLabel18.setText("Số ĐT");
        pnlemplist.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 40, 20));
        pnlemplist.add(txtphone_empl, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 200, -1));

        jLabel19.setText("Email");
        pnlemplist.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 40, 20));
        pnlemplist.add(txtemail_empl, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 200, -1));

        getContentPane().add(pnlemplist, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 770, 560));

        pnlcusomer.setBackground(new java.awt.Color(255, 255, 255));
        pnlcusomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlcusomer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblcust.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_customer", "HoTen", "DiaChi", "SoDT", "Email"
            }
        ));
        tblcust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblcustMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblcust);

        pnlcusomer.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 690, 350));

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnlcusomer.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 153, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnlcusomer.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, -1, -1));

        jLabel17.setText("Id_Customer");
        pnlcusomer.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 70, 20));

        txtid_cust.setEditable(false);
        pnlcusomer.add(txtid_cust, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 270, -1));

        jLabel20.setText("Họ Tên");
        pnlcusomer.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 70, 20));
        pnlcusomer.add(txtname_cust, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 270, -1));

        jLabel21.setText("Địa Chỉ");
        pnlcusomer.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 70, 20));
        pnlcusomer.add(txtadress_cust, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 270, -1));

        jLabel22.setText("Số ĐT");
        pnlcusomer.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 40, 20));
        pnlcusomer.add(txtphone_cust, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 230, -1));

        jLabel23.setText("Email");
        pnlcusomer.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 40, 20));
        pnlcusomer.add(txtemail_cust, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 230, -1));

        getContentPane().add(pnlcusomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 770, 560));

        pnlStatistics.setBackground(new java.awt.Color(255, 255, 255));
        pnlStatistics.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton4.setBackground(new java.awt.Color(51, 153, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("BACK");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Type Trans:");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Date:");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtFindID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel4.add(txtFindID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 202, 30));

        dcDate.setFocusable(false);
        jPanel4.add(dcDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 202, 30));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setText("ID empolyee:");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 20));

        cbbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Type", "Rút tiền", "Nạp tiền", "Chuyển tiền" }));
        jPanel4.add(cbbType, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 130, 30));

        btnSearch.setBackground(new java.awt.Color(51, 153, 255));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel4.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Withdraw");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Deposit");

        lblMoneyNap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMoneyNap.setText("000000");

        lblMoneyRut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMoneyRut.setText("000000");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMoneyRut)
                    .addComponent(lblMoneyNap))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(lblMoneyRut))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(lblMoneyNap))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        tblTrans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "AccNo", "Date", "Details", "TypeTrans", "Money", "ID_Employee"
            }
        ));
        jScrollPane4.setViewportView(tblTrans);

        javax.swing.GroupLayout pnlStatisticsLayout = new javax.swing.GroupLayout(pnlStatistics);
        pnlStatistics.setLayout(pnlStatisticsLayout);
        pnlStatisticsLayout.setHorizontalGroup(
            pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatisticsLayout.createSequentialGroup()
                .addGroup(pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStatisticsLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlStatisticsLayout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlStatisticsLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        pnlStatisticsLayout.setVerticalGroup(
            pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatisticsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(pnlStatistics, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 770, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        saveNewEmployee();
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        update_emp();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void lblCEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCEMouseClicked
        // TODO add your handling code here:
        showPanelMenu(pnlemp);
        lbltitle.setText("Create Employee");
    }//GEN-LAST:event_lblCEMouseClicked

    private void lblCEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCEMouseEntered
        // TODO add your handling code here:
        hoverMenu(lblCE);
    }//GEN-LAST:event_lblCEMouseEntered

    private void lblUEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUEMouseClicked
        // TODO add your handling code here:
        showPanelMenu(pnlemplist);
        lbltitle.setText("Employee List");
        loadDataToTable(tbllistemp);
    }//GEN-LAST:event_lblUEMouseClicked

    private void lblUEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUEMouseEntered
        // TODO add your handling code here:
        hoverMenu(lblUE);
    }//GEN-LAST:event_lblUEMouseEntered

    private void lblUEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUEMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_lblUEMouseExited

    private void lblCEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCEMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_lblCEMouseExited

    private void lblUCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUCMouseClicked
        // TODO add your handling code here:
        showPanelMenu(pnlcusomer);
        lbltitle.setText("Customer List");
        loadDataToTable(tblcust);
    }//GEN-LAST:event_lblUCMouseClicked

    private void lblUCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUCMouseEntered
        // TODO add your handling code here:
        hoverMenu(lblUC);
    }//GEN-LAST:event_lblUCMouseEntered

    private void lblUCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUCMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_lblUCMouseExited

    private void lblLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseClicked
        // TODO add your handling code here:
        logOut();
    }//GEN-LAST:event_lblLogOutMouseClicked

    private void lblLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseEntered
        // TODO add your handling code here:
        hoverMenu(lblLogOut);
    }//GEN-LAST:event_lblLogOutMouseEntered

    private void lblLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseExited
        // TODO add your handling code here:
        setColorMenuItem();
    }//GEN-LAST:event_lblLogOutMouseExited

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int option = fc.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            String pathImgDefault = file.getPath();
            pathImg = "nv_" + pathImgDefault.split("_")[1];
            resizeImage(pathImg);
        }

    }//GEN-LAST:event_jLabel15MouseClicked

    private void tbllistempMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbllistempMousePressed
        // TODO add your handling code here:
        int row = tbllistemp.getSelectedRow();
        String id = tbllistemp.getValueAt(row, 0).toString();
        String name = tbllistemp.getValueAt(row, 1).toString();
        String adress = tbllistemp.getValueAt(row, 2).toString();
        String phone = tbllistemp.getValueAt(row, 3).toString();
        String email = tbllistemp.getValueAt(row, 4).toString();

        txtid_empl.setText(id);
        txtname_empl.setText(name);
        txtadress_empl.setText(adress);
        txtphone_empl.setText(phone);
        txtemail_empl.setText(email);

    }//GEN-LAST:event_tbllistempMousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        delete_cust();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        // TODO add your handling code here:
        delete_emp();
    }//GEN-LAST:event_btndelActionPerformed

    private void tblcustMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcustMousePressed
        // TODO add your handling code here:
        int row = tblcust.getSelectedRow();
        String id = tblcust.getValueAt(row, 0).toString();
        String name = tblcust.getValueAt(row, 1).toString();
        String adress = tblcust.getValueAt(row, 2).toString();
        String phone = tblcust.getValueAt(row, 3).toString();
        String email = tblcust.getValueAt(row, 4).toString();

        txtid_cust.setText(id);
        txtname_cust.setText(name);
        txtadress_cust.setText(adress);
        txtphone_cust.setText(phone);
        txtemail_cust.setText(email);
    }//GEN-LAST:event_tblcustMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        update_cust();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lblStatisticsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStatisticsMouseClicked
        // TODO add your handling code here:
        showPanelMenu(pnlStatistics);
        lbltitle.setText("Statistics");
        loadDataToTable(tblTrans);
    }//GEN-LAST:event_lblStatisticsMouseClicked

    private void lblStatisticsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStatisticsMouseEntered
        // TODO add your handling code here:
        GuiUtil.hoverMenu(lblStatistics);
    }//GEN-LAST:event_lblStatisticsMouseEntered

    private void lblStatisticsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStatisticsMouseExited
        // TODO add your handling code here:
        GuiUtil.setColorMenuItem(lblCE, lblUE, lblUC, lblStatistics, lblLogOut);
    }//GEN-LAST:event_lblStatisticsMouseExited

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        // TODO add your handling code here:
        clearCreateAcc();
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        loadTableFilter();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMouseClicked
        // TODO add your handling code here:
        showHelp();
    }//GEN-LAST:event_btnHelpMouseClicked

    private void init() {
        setLocationRelativeTo(null);
        XDate.showTime(lblDate, "dd/MM/yyyy");
        XDate.showTime(lblClock, "hh:mm:ss a");
        showPanelMenu(pnlemp);
        tableDesign(tblcust);
        tableDesign(tbllistemp);
        tableDesign(tblTrans);
    }

    private void showHelp() {
        try {
            Desktop.getDesktop().browse(new File("help/index.html").toURI());
        } catch (IOException e) {
            MsgBoxUtil.alert(this, "Instruction file not found");
        }
    }

    private void showPanelMenu(JPanel pnl) {
        pnlcusomer.setVisible(false);
        pnlemplist.setVisible(false);
        pnlemp.setVisible(false);
        pnlStatistics.setVisible(false);
        renderNewId();
        pnl.setVisible(true);
    }

    private void hoverMenu(JLabel lbl) {
        //setColorMenuItem();
        // set color button
        lbl.setBackground(new Color(51, 153, 255));
        lbl.setForeground(Color.white);

    }

    private void setColorMenuItem() {
        // set color button
        lblCE.setBackground(new Color(255, 255, 255));
        lblClock.setBackground(new Color(255, 255, 255));
        lblLogOut.setBackground(new Color(255, 255, 255));
        lblDate.setBackground(new Color(255, 255, 255));
        lblUC.setBackground(new Color(255, 255, 255));
        lblUE.setBackground(new Color(255, 255, 255));
        lblCE.setForeground(Color.black);
        lblClock.setForeground(Color.white);
        lblLogOut.setForeground(Color.black);
        lblDate.setForeground(Color.white);
        lblUC.setForeground(Color.black);
        lblUE.setForeground(Color.black);

    }

    private void logOut() {
        boolean b = MsgBoxUtil.confirm(this, "Do you want to logout?");
        if (b) {
            AdminDAO dao = new AdminDAO();
            this.dispose();
            Login login = new Login();
            login.setVisible(true);
        }
    }

    private void loadDataToTable(JTable table) {
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        dtm.setRowCount(0);

        if (table == tbllistemp) {
            List<EmployeeModel> listemp = epDao.findAll();
            for (EmployeeModel emp : listemp) {
                dtm.addRow(new EmployeeMapper().mapper(emp));
            }
        } else if (table == tblcust) {
            List<CustomerModel> listCust = ctDao.findAll();
            for (CustomerModel cus : listCust) {
                dtm.addRow(new CustomerMapper().mapper(cus));
            }
        } else if (table == tblTrans) {
            List<TransactionModel> listTrans = ttDao.findAll();
            for (TransactionModel model : listTrans) {
                dtm.addRow(new TransactionMapper().mapper(model));
            }
        }
    }

    private void tableDesign(JTable tbl) {
        DefaultTableCellRenderer head_render = new DefaultTableCellRenderer();
        head_render.setPreferredSize(new Dimension(30, 40));
        head_render.setBackground(new Color(32, 136, 203));
        head_render.setForeground(new Color(255, 255, 255));
        head_render.setFont(new Font("Segoe UI", Font.BOLD, 14));
        //do rong cac cot
//        setColumnWidths(tbl,30, 150, 100, 100);
        tbl.getTableHeader().setDefaultRenderer(head_render);
        tbl.setRowHeight(35);
        tbl.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tbl.setBackground(Color.white);
    }

    void delete_emp() {
        if (MsgBoxUtil.confirm(this, "Do you want to delete?")) {
            String id = txtid_empl.getText();
            try {
                epDao.delete(id);
                this.loadDataToTable(tbllistemp);
                MsgBoxUtil.alert(this, "Delete Succesfully!");
            } catch (HeadlessException e) {
                MsgBoxUtil.alert(this, "Delete Fail!");
            }
        }
    }

    private void saveNewEmployee() {
        if (CreateAccValidation()) {
            boolean a = MsgBoxUtil.confirm(this, "Do you want to create new Employee?");
            if (a) {
                EmployeeModel newModel = new EmployeeModel();
                newModel.setId(txtEID.getText());
                newModel.setHoTen(txtname.getText());
                newModel.setDiaChi(txtAdress.getText());
                newModel.setSoDT(txtContact.getText());

                newModel.setNgaySinh(dcBirth.getDate());
                newModel.setEmail(txtEmail.getText());
                newModel.setUsername(txtUN1.getText());
                newModel.setPassword(txtUN.getText());
                newModel.setLinkImg(pathImg);

                epDao.saveOne(newModel);

            }
        }
    }

    private void update_emp() {
        boolean a = MsgBoxUtil.confirm(this, "Do you want to Update Employee?");
        if (a) {
            EmployeeModel Model = new EmployeeModel();
            Model.setHoTen(txtname_empl.getText());
            Model.setDiaChi(txtadress_empl.getText());
            Model.setSoDT(txtphone_empl.getText());
            Model.setEmail(txtemail_empl.getText());
            Model.setId(txtid_empl.getText());
  
            epDao.update(Model);
            this.loadDataToTable(tbllistemp);
        }
    }

    private void update_cust() {
        boolean a = MsgBoxUtil.confirm(this, "Do you want to delete this Customer?");
        if (a) {
            CustomerModel Model = new CustomerModel();
            Model.setHoTen(txtname_cust.getText());
            Model.setDiaChi(txtadress_cust.getText());
            Model.setSoDT(txtphone_cust.getText());
            Model.setEmail(txtemail_cust.getText());
            Model.setId(txtid_cust.getText());
            ctDao.update(Model);
            this.loadDataToTable(tblcust);
        }
    }

    void delete_cust() {
        if (MsgBoxUtil.confirm(this, "Do you want to delete this Customer?")) {
            String id = txtid_cust.getText();
            try {
                String soTK = acDao.findByIdKH(id).getSoTK();
                ttDao.deleteBySoTK(soTK);
                acDao.deleteByIdKH(id);
                ctDao.delete(id);
                this.loadDataToTable(tblcust);
                MsgBoxUtil.alert(this, "Delete Succesfully!");
            } catch (HeadlessException e) {
                MsgBoxUtil.alert(this, "Delete Fail!");
            }
        }
    }

    private boolean CreateAccValidation() {
        String error = "";
        //Name
        if (Validator.checkEmpty(txtname)) {
            error += "Name cannot be null!\n";
        }
        //Address
        if (Validator.checkEmptyArea(txtAdress)) {
            error += "Address cannot be null!\n";
        }
        //Contact
        if (Validator.checkEmpty(txtContact)) {
            error += "Contact cannot be null!\n";
        }
        if (Validator.checkPhone(txtContact)) {
            error += "Contact must be 10 numbers!\n";
        }
        //Birth
        if (Validator.checkDate(dcBirth)) {
            error += "Birth must be in dd-MM-yyyy!\n";
        }
        //Email
        if (Validator.checkEmpty(txtEmail)) {
            error += "Email cannot be null!\n";
        }
        if (Validator.checkEmail(txtEmail)) {
            error += "Wrong email format!\n";
        }
        //Submit
        if (!error.equals("")) {
            JOptionPane.showMessageDialog(null, error);
            return false;
        } else {
            return true;
        }
    }

    private void renderNewId() {
        String new_id = "";

        String id = epDao.findOne().getId();
        int id_num = Integer.valueOf(id.split("_")[1].substring(0, 3));

        if (id_num + 1 < 10) {
            new_id = "00" + (id_num + 1);
        } else {
            new_id = "0" + (id_num + 1);
        }
        txtEID.setText("NV_" + new_id);
    }

    private void resizeImage(String link) {
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/com/bmSys/image/" + link));
        Image img = imageIcon.getImage();
        Image dimg = img.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(),
                Image.SCALE_SMOOTH);
        ImageIcon scaleIcon = new ImageIcon(dimg);
        lblImage.setIcon(scaleIcon);
    }

    public void refresh1(JTextField... arrTf) {
        for (JTextField tf : arrTf) {
            tf.setText("");
            tf.setBackground(Color.white);
        }
    }

    public void loadTableFilter() {
        DefaultTableModel dtm = (DefaultTableModel) tblTrans.getModel();
        dtm.setRowCount(0);
        List<TransactionModel> listTrans = ttDao.findMany(txtFindID.getText(), dcDate.getDate(), (String) cbbType.getSelectedItem());
        for (TransactionModel model : listTrans) {
            dtm.addRow(new TransactionMapper().mapper(model));
        }
        sumMoney();
    }

    public void sumMoney() {
        float moneyNap = 0;
        float moneyRut = 0;
        int numRow = tblTrans.getRowCount();
        for (int i = 0; i < numRow; i++) {
            String type = tblTrans.getValueAt(i, 4).toString();
            if (type.startsWith("R")) {
                moneyRut += Float.valueOf(tblTrans.getValueAt(i, 5).toString());
            } else if (type.startsWith("N")) {
                moneyNap += Float.valueOf(tblTrans.getValueAt(i, 5).toString());
            }
        }
        lblMoneyNap.setText(Float.toString(moneyNap));
        lblMoneyRut.setText(Float.toString(moneyRut));
    }

    private void clearCreateAcc() {
        refresh1(txtname, txtUN1, txtUN, txtEmail, txtContact);
        txtAdress.setText("");
        txtAdress.setBackground(Color.white);
        dcBirth.setCalendar(null);
        dcBirth.setBackground(Color.white);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnHelp;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cbbType;
    private com.toedter.calendar.JDateChooser dcBirth;
    private com.toedter.calendar.JDateChooser dcDate;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCE;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLogOut;
    private javax.swing.JLabel lblMoneyNap;
    private javax.swing.JLabel lblMoneyRut;
    private javax.swing.JLabel lblStatistics;
    private javax.swing.JLabel lblUC;
    private javax.swing.JLabel lblUE;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JPanel pnlStatistics;
    private javax.swing.JPanel pnlcusomer;
    private javax.swing.JPanel pnlemp;
    private javax.swing.JPanel pnlemplist;
    private javax.swing.JTable tblTrans;
    private javax.swing.JTable tblcust;
    private javax.swing.JTable tbllistemp;
    private javax.swing.JTextArea txtAdress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEID;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFindID;
    private javax.swing.JTextField txtUN;
    private javax.swing.JTextField txtUN1;
    private javax.swing.JTextField txtadress_cust;
    private javax.swing.JTextField txtadress_empl;
    private javax.swing.JTextField txtemail_cust;
    private javax.swing.JTextField txtemail_empl;
    private javax.swing.JTextField txtid_cust;
    private javax.swing.JTextField txtid_empl;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtname_cust;
    private javax.swing.JTextField txtname_empl;
    private javax.swing.JTextField txtphone_cust;
    private javax.swing.JTextField txtphone_empl;
    // End of variables declaration//GEN-END:variables
}
